name=01-05-20130913V-HA-colisional
all:
	xelatex ${name}.tex
#	bibtex ${name} 
#	xelatex ${name}.tex
#	xelatex ${name}.tex

clean:
	rm -f *.aux *.lof *.log *.lot *.out *.toc *.nlo *.bbl *.blg *.brf *.ilg *.ind *.nls *.nav *.snm *.bak *.synctex.gz

del:
	make clean
	rm ${name}.pdf
